#!/usr/bin/env Rscript
#install.packages("ggplot2")
#install.packages("scales")
args = commandArgs(trailingOnly=TRUE)
df = read.table(args[1])
outpdf=(args[2])
## head(df)
mdn=median(df$V14)
correction=1/mdn
print(correction)
df_new=data.frame(df$V14*correction)
df2 = cbind(df, df_new)
log2=data.frame(log(df2[16], 2))
head(log2)
df3 = cbind(df2, log2)
colnames(df3)[c(16,17)] <-c("corrected","log2corrected")
head(df3)
library(ggplot2)
library(scales)
ggplot(df3, aes(x=V1, y=log2corrected, colour=log2corrected)) + xlab ("gene amplicon") + ylab ("relative amplicon copy number - log2") + theme(axis.text.x = element_text(angle = 70, hjust = 1, size = 6)) + scale_x_discrete(breaks = levels(df$V1)[c(T, rep(F, 4))])  +geom_point()  + scale_y_continuous(breaks = pretty_breaks()) + ylim(-7, 7)
ggsave(outpdf, width=12)
remove('df', 'mdn', 'correction', 'df_new', 'df2', 'log2', 'df3')
